openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8081
    description: Generated server url
paths:
  /{username}:
    get:
      tags:
        - chatterbook-controller
      operationId: getUsername
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
  /{username}/chatterPosts:
    get:
      tags:
        - chatterbook-controller
      operationId: getUserChatterPostsByUsername
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChatterPost'
  /users:
    get:
      tags:
        - chatterbook-controller
      operationId: getuser
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: string
  /:
    get:
      tags:
        - chatterbook-controller
      operationId: getAllUsers
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    ChatterPost:
      type: object
      properties:
        gettext:
          type: string
    User:
      type: object
      properties:
        name:
          type: string
        chatterPosts:
          type: array
          items:
            $ref: '#/components/schemas/ChatterPost'
